//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace XDP.XDPCore {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPData", IsNullable=false)]
    public partial class XDPInternalCommonHeader {
        
        private string xDPEncryptionAlgorithmField;
        
        private string xDPEncryptionModeField;
        
        private string xDPEncryptionIVField;
        
        private string xDPSignatureAlgorithmField;
        
        private byte[] xDPDataSignatureField;
        
        /// <remarks/>
        public string XDPEncryptionAlgorithm {
            get {
                return this.xDPEncryptionAlgorithmField;
            }
            set {
                this.xDPEncryptionAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        public string XDPEncryptionMode {
            get {
                return this.xDPEncryptionModeField;
            }
            set {
                this.xDPEncryptionModeField = value;
            }
        }
        
        /// <remarks/>
        public string XDPEncryptionIV {
            get {
                return this.xDPEncryptionIVField;
            }
            set {
                this.xDPEncryptionIVField = value;
            }
        }
        
        /// <remarks/>
        public string XDPSignatureAlgorithm {
            get {
                return this.xDPSignatureAlgorithmField;
            }
            set {
                this.xDPSignatureAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPDataSignature {
            get {
                return this.xDPDataSignatureField;
            }
            set {
                this.xDPDataSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPData", IsNullable=false)]
    public partial class XDPAuthorizedIdentities {
        
        private string[] identityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identity")]
        public string[] Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPData", IsNullable=false)]
    public partial class XDPInternalMachineHeader {
        
        private string hostnameField;
        
        private string[] xDPAuthorizedIdentitiesField;
        
        private byte[] xDPEncryptedKeysField;
        
        /// <remarks/>
        public string Hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Identity", IsNullable=false)]
        public string[] XDPAuthorizedIdentities {
            get {
                return this.xDPAuthorizedIdentitiesField;
            }
            set {
                this.xDPAuthorizedIdentitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPEncryptedKeys {
            get {
                return this.xDPEncryptedKeysField;
            }
            set {
                this.xDPEncryptedKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPData", IsNullable=false)]
    public partial class XDPInternalDomainHeader {
        
        private string xDPDomainServerField;
        
        private string[] xDPAuthorizedIdentitiesField;
        
        private byte[] xDPEncryptedKeysField;
        
        /// <remarks/>
        public string XDPDomainServer {
            get {
                return this.xDPDomainServerField;
            }
            set {
                this.xDPDomainServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Identity", IsNullable=false)]
        public string[] XDPAuthorizedIdentities {
            get {
                return this.xDPAuthorizedIdentitiesField;
            }
            set {
                this.xDPAuthorizedIdentitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPEncryptedKeys {
            get {
                return this.xDPEncryptedKeysField;
            }
            set {
                this.xDPEncryptedKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPData", IsNullable=false)]
    public partial class XDPHeader {
        
        private ushort xDPVersionField;
        
        private XDPHeaderXDPInternalHeader xDPInternalHeaderField;
        
        /// <remarks/>
        public ushort XDPVersion {
            get {
                return this.xDPVersionField;
            }
            set {
                this.xDPVersionField = value;
            }
        }
        
        /// <remarks/>
        public XDPHeaderXDPInternalHeader XDPInternalHeader {
            get {
                return this.xDPInternalHeaderField;
            }
            set {
                this.xDPInternalHeaderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    public partial class XDPHeaderXDPInternalHeader {
        
        private XDPInternalCommonHeader xDPInternalCommonHeaderField;
        
        private XDPInternalMachineHeader[] xDPInternalMachineHeaderField;
        
        private XDPInternalDomainHeader xDPInternalDomainHeaderField;
        
        private XDPHeaderXDPInternalHeaderXDPInternalHeaderSignatures xDPInternalHeaderSignaturesField;
        
        /// <remarks/>
        public XDPInternalCommonHeader XDPInternalCommonHeader {
            get {
                return this.xDPInternalCommonHeaderField;
            }
            set {
                this.xDPInternalCommonHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XDPInternalMachineHeader")]
        public XDPInternalMachineHeader[] XDPInternalMachineHeader {
            get {
                return this.xDPInternalMachineHeaderField;
            }
            set {
                this.xDPInternalMachineHeaderField = value;
            }
        }
        
        /// <remarks/>
        public XDPInternalDomainHeader XDPInternalDomainHeader {
            get {
                return this.xDPInternalDomainHeaderField;
            }
            set {
                this.xDPInternalDomainHeaderField = value;
            }
        }
        
        /// <remarks/>
        public XDPHeaderXDPInternalHeaderXDPInternalHeaderSignatures XDPInternalHeaderSignatures {
            get {
                return this.xDPInternalHeaderSignaturesField;
            }
            set {
                this.xDPInternalHeaderSignaturesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPData")]
    public partial class XDPHeaderXDPInternalHeaderXDPInternalHeaderSignatures {
        
        private byte[][] xDPInternalHeaderMachineSignatureField;
        
        private byte[] xDPInternalHeaderDomainSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XDPInternalHeaderMachineSignature", DataType="hexBinary")]
        public byte[][] XDPInternalHeaderMachineSignature {
            get {
                return this.xDPInternalHeaderMachineSignatureField;
            }
            set {
                this.xDPInternalHeaderMachineSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPInternalHeaderDomainSignature {
            get {
                return this.xDPInternalHeaderDomainSignatureField;
            }
            set {
                this.xDPInternalHeaderDomainSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPKeys {
        
        private byte[] xDPEncryptionKeyField;
        
        private byte[] xDPSignatureKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPEncryptionKey {
            get {
                return this.xDPEncryptionKeyField;
            }
            set {
                this.xDPEncryptionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] XDPSignatureKey {
            get {
                return this.xDPSignatureKeyField;
            }
            set {
                this.xDPSignatureKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPRequestDomainHeader {
        
        private XDPInternalCommonHeader xDPInternalCommonHeaderField;
        
        private string[] xDPAuthorizedIdentitiesField;
        
        private XDPKeys xDPKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData")]
        public XDPInternalCommonHeader XDPInternalCommonHeader {
            get {
                return this.xDPInternalCommonHeaderField;
            }
            set {
                this.xDPInternalCommonHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:com.XDP.XDPData")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identity", IsNullable=false)]
        public string[] XDPAuthorizedIdentities {
            get {
                return this.xDPAuthorizedIdentitiesField;
            }
            set {
                this.xDPAuthorizedIdentitiesField = value;
            }
        }
        
        /// <remarks/>
        public XDPKeys XDPKeys {
            get {
                return this.xDPKeysField;
            }
            set {
                this.xDPKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPResponseDomainHeader {
        
        private XDPInternalDomainHeader xDPInternalDomainHeaderField;
        
        private byte[] xDPInternalHeaderDomainSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData")]
        public XDPInternalDomainHeader XDPInternalDomainHeader {
            get {
                return this.xDPInternalDomainHeaderField;
            }
            set {
                this.xDPInternalDomainHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData", DataType="hexBinary")]
        public byte[] XDPInternalHeaderDomainSignature {
            get {
                return this.xDPInternalHeaderDomainSignatureField;
            }
            set {
                this.xDPInternalHeaderDomainSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPRequestDecryptionKey {
        
        private XDPInternalCommonHeader xDPInternalCommonHeaderField;
        
        private XDPInternalDomainHeader xDPInternalDomainHeaderField;
        
        private byte[] xDPInternalHeaderDomainSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData")]
        public XDPInternalCommonHeader XDPInternalCommonHeader {
            get {
                return this.xDPInternalCommonHeaderField;
            }
            set {
                this.xDPInternalCommonHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData")]
        public XDPInternalDomainHeader XDPInternalDomainHeader {
            get {
                return this.xDPInternalDomainHeaderField;
            }
            set {
                this.xDPInternalDomainHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData", DataType="hexBinary")]
        public byte[] XDPInternalHeaderDomainSignature {
            get {
                return this.xDPInternalHeaderDomainSignatureField;
            }
            set {
                this.xDPInternalHeaderDomainSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPResponseDecryptionKey {
        
        private XDPKeys xDPKeysField;
        
        /// <remarks/>
        public XDPKeys XDPKeys {
            get {
                return this.xDPKeysField;
            }
            set {
                this.xDPKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:com.XDP.XDPMessages", IsNullable=false)]
    public partial class XDPException {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XDPBadParameter", typeof(XDPExceptionXDPBadParameter))]
        [System.Xml.Serialization.XmlElementAttribute("XDPBadSignature", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPGeneralException", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPNotAuthorized", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPUnknownIdentity", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPUpdateCommonHeader", typeof(XDPExceptionXDPUpdateCommonHeader))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    public partial class XDPExceptionXDPBadParameter {
        
        private string parameterField;
        
        private string reasonField;
        
        /// <remarks/>
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com.XDP.XDPMessages")]
    public partial class XDPExceptionXDPUpdateCommonHeader {
        
        private XDPInternalCommonHeader xDPInternalCommonHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:com.XDP.XDPData")]
        public XDPInternalCommonHeader XDPInternalCommonHeader {
            get {
                return this.xDPInternalCommonHeaderField;
            }
            set {
                this.xDPInternalCommonHeaderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.XDP.XDPMessages", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        XDPBadParameter,
        
        /// <remarks/>
        XDPBadSignature,
        
        /// <remarks/>
        XDPGeneralException,
        
        /// <remarks/>
        XDPNotAuthorized,
        
        /// <remarks/>
        XDPUnknownIdentity,
        
        /// <remarks/>
        XDPUpdateCommonHeader,
    }
}
