//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace XDP.MachineService.Messages {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:XDP.XDPMachineService.Messages")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:XDP.XDPMachineService.Messages", IsNullable=false)]
    public partial class XDPExceptionResponse {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XDPBadParameter", typeof(XDPExceptionResponseXDPBadParameter))]
        [System.Xml.Serialization.XmlElementAttribute("XDPBadSignature", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPGeneralException", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPNotAuthorized", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XDPUnknownIdentity", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:XDP.XDPMachineService.Messages")]
    public partial class XDPExceptionResponseXDPBadParameter {
        
        private string parameterField;
        
        private string reasonField;
        
        /// <remarks/>
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:XDP.XDPMachineService.Messages", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        XDPBadParameter,
        
        /// <remarks/>
        XDPBadSignature,
        
        /// <remarks/>
        XDPGeneralException,
        
        /// <remarks/>
        XDPNotAuthorized,
        
        /// <remarks/>
        XDPUnknownIdentity,
    }
}
